export const Report_Types = [
    "report_reporttypes_0",
    "report_reporttypes_1",
    "report_reporttypes_2",
    "report_reporttypes_3",
    "report_reporttypes_4",
    "report_reporttypes_5",
    "report_reporttypes_6",
    "report_reporttypes_7",
    "report_reporttypes_8",
    "report_reporttypes_9",
    "report_reporttypes_10",
    "report_reporttypes_11",
    "report_reporttypes_12",
];
